### ISSUE TITLE
GUI To-do list.

### ISSUE THREAD

**Issue by jadenyjw** [jadenyjw/drawpvp#1]
- [x] Implement all the functionality of the Menu Screens.
- [x] Implement the Game Screen.
- [x] Make things scale. Prioritize position scaling over size/DPI scaling.
- [x] Make things look pretty.
